name: Generate and sync

on:
  # Run if push to `master` branch
  push:
    branches:
      - master

jobs:
  generate-and-sync:
    # Use latest Ubuntu Linux
    runs-on: ubuntu-latest
    steps:
    # Use Deno
    - name: Use Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    # Config Git
    - name: Enable Git colorful output
      run: git config --global color.ui true
    # Get src from kuohuanhuan/blog
    - name: Get source file (blog)
      uses: actions/checkout@v3
      with:
        repository: 'kuohuanhuan/blog'
        path: 'current'
    # Get src from kuohuanhuan/nekohuan.cyou
    - name: Get source file (site)
      uses: actions/checkout@v3
      with:
        repository: 'kuohuanhuan/nekohuan.cyou'
        path: 'target'
        token: ${{ secrets.GH_PAT }} # Personal Access Token
    # Edit posts list file
    - name: Edit posts.json
      run: |
        cd current
        deno run --allow-read --allow-write index.ts
        cd ..
    # Update posts list file
    - name: Update posts.json
      uses: EndBug/add-and-commit@v9
      with:
        add: 'posts.json'
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        cwd: './current'
        message: 'chore: update posts list (pushed by Actions CI)'
    # Edit commit hash file
    - name: Edit source.ts
      run: |
        cd current
        COMMIT_HASH=$(git rev-parse HEAD)
        cd ../target
        rm config/source.ts
        echo "export const COMMIT_HASH = '$COMMIT_HASH' // Generated by GitHub Actions, don't modify." >> config/source.ts
        cd ..
    # Sync commit hash file
    - name: Sync source.ts
      uses: EndBug/add-and-commit@v9
      with:
        add: 'config/source.ts'
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        cwd: './target'
        message: 'chore: sync latest commit hash (pushed by Actions CI)'

# Authored by KuoHuanHuan.
